
package forms;
import develop.Mostrar;

public class FrmMostrar extends javax.swing.JInternalFrame {
Mostrar optionsShow =  new Mostrar();
    /**
     * Creates new form Mostrar
     */
    public FrmMostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnmostrar = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        rbtn6 = new javax.swing.JRadioButton();
        rbtn5 = new javax.swing.JRadioButton();
        rbtn4 = new javax.swing.JRadioButton();
        rbtn3 = new javax.swing.JRadioButton();
        btnM = new javax.swing.JButton();
        rbtn2 = new javax.swing.JRadioButton();
        rbtn1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOptions = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(85, 65, 16));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtnmostrar.add(rbtn6);
        rbtn6.setText("La cantidad de productos que tenemos en cada categoría");
        jPanel2.add(rbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        rbtnmostrar.add(rbtn5);
        rbtn5.setText("Lista de categorías (sin que aparezcan datos duplicados)");
        jPanel2.add(rbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        rbtnmostrar.add(rbtn4);
        rbtn4.setText("El precio medio de aquellos cuyo nombre comienza con \"Taza\"");
        jPanel2.add(rbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        rbtnmostrar.add(rbtn3);
        rbtn3.setText("Nombre y el precio de los que cumplen una condición, price<22");
        jPanel2.add(rbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        btnM.setText("Search");
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });
        jPanel2.add(btnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        rbtnmostrar.add(rbtn2);
        rbtn2.setText("Datos que comienzan por una cierta inicial");
        jPanel2.add(rbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        rbtnmostrar.add(rbtn1);
        rbtn1.setSelected(true);
        rbtn1.setText("Datos que tienen un cierto nombre");
        jPanel2.add(rbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        tableOptions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableOptions);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 350, 350));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Mostrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(199, 199, 199))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 870, 479));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
     String option;
     if(this.rbtn1.isSelected()){
         option =  "option1";
      
         this.tableOptions.setModel(optionsShow.TitulosOptions1());
         this.tableOptions.setModel(optionsShow.DataOptions1(option));
     } else if (this.rbtn2.isSelected()) {
         option = "option2";
         this.tableOptions.setModel(optionsShow.TitulosOptions1());
         this.tableOptions.setModel(optionsShow.DataOptions1(option));
     } else if (this.rbtn3.isSelected()) {
         option = "option3";

         this.tableOptions.setModel(optionsShow.TitulosOptions2());
         this.tableOptions.setModel(optionsShow.DataOptions2(option));
     } else if (this.rbtn4.isSelected()) {
         option = "option4";
          this.tableOptions.setModel(optionsShow.TitulosOptions3());
         this.tableOptions.setModel(optionsShow.DataOptions3(option));
     } else if (this.rbtn5.isSelected()) {
         option = "option5";
       this.tableOptions.setModel(optionsShow.TitulosOptions4());
         this.tableOptions.setModel(optionsShow.DataOptions4(option));
     } else {
         option = "option6";
          this.tableOptions.setModel(optionsShow.TitulosOptions5());
         this.tableOptions.setModel(optionsShow.DataOptions5(option));
     }
       
    }//GEN-LAST:event_btnMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtn1;
    private javax.swing.JRadioButton rbtn2;
    private javax.swing.JRadioButton rbtn3;
    private javax.swing.JRadioButton rbtn4;
    private javax.swing.JRadioButton rbtn5;
    private javax.swing.JRadioButton rbtn6;
    private javax.swing.ButtonGroup rbtnmostrar;
    private javax.swing.JTable tableOptions;
    // End of variables declaration//GEN-END:variables
}
